package project.rayedchan.utilities;

import javax.xml.xpath.XPath;
import javax.xml.xpath.XPathConstants;
import javax.xml.xpath.XPathExpressionException;
import javax.xml.xpath.XPathFactory;
import org.w3c.dom.Document;
import org.w3c.dom.NodeList;

/**
 * @author rayedchan
 * This class contains method responsible for changing the display name
 * of a UDF. The display name of the UDF is only used in the front-end.
 * The "/xliffBundles/oracle/iam/ui/runtime/BizEditorBundle.xlf" file
 * is responsible for storing the display name on the User Form.
 * 
 * This utility is suppose to be used after a successful import of the 
 * UDF Metadata file generated by the UserDefinedFieldBackendTestDriver.java.
 */
public class UserFormDisplayNameUtility 
{
    /**
     * Change the display name of a UDF in the given document object.
     * @param bizEditorBundleDoc    Document of "/xliffBundles/oracle/iam/ui/runtime/BizEditorBundle.xlf" file
     * @param columnName            Column Name of the User Defined Field
     * @param newDisplayName        The new display name of the User Defined Field
     */
    public boolean changeUDFDisplayName(Document bizEditorBundleDoc, String columnName, String newDisplayName) throws XPathExpressionException
    {     
        XPathFactory xPathFactory = XPathFactory.newInstance();
        XPath xpath = xPathFactory.newXPath();
        NodeList nodesRunTime =  (NodeList) xpath.evaluate("/xliff/file/body/trans-unit[@id='sessiondef.oracle.iam.ui.runtime.form.model.user.entity.userEO." + columnName + "__c_LABEL']/source", bizEditorBundleDoc, XPathConstants.NODESET);
        NodeList nodesCommon =  (NodeList) xpath.evaluate("/xliff/file/body/trans-unit[@id='oracle.iam.ui.common.model.user.entity.UserEO." + columnName + "__c_LABEL']/source", bizEditorBundleDoc, XPathConstants.NODESET);
        
        // Column name not found in the document object
        if(nodesRunTime.getLength() == 0 || nodesCommon.getLength() == 0)
        {
            return false;
        }
        
        // Change the display name in two XML tags
        nodesRunTime.item(0).setTextContent(newDisplayName);
        nodesCommon.item(0).setTextContent(newDisplayName);

        return true;
    }
    
}
